# Generated by Django 6.0.1 on 2026-03-08 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('kategoriler', models.ManyToManyField(related_name='kitaplar', to='kutuphane.kategori')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitaplar', to='kutuphane.yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Biyografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField()),
                ('yazar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kutuphane.yazar')),
            ],
        ),
    ]
